<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Package.xml" />
  <PropertyGroup>
    <Description>ThinkingHome plugin which provide API for wireless control of appliances using the nooLite system.</Description>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ThinkingHome.Core.Plugins/ThinkingHome.Core.Plugins.csproj" />
    <ProjectReference Include="../ThinkingHome.Plugins.Scripts/ThinkingHome.Plugins.Scripts.csproj" />
    <ProjectReference Include="../ThinkingHome.Plugins.Timer/ThinkingHome.Plugins.Timer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />
    <PackageReference Include="ThinkingHome.NooLite" Version="5.0.0" />
  </ItemGroup>
</Project>
