<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="../Package.xml" />
    <PropertyGroup>
        <Description>ThinkingHome plugin which provide the ability to call other plugins methods by HTTP requests.</Description>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="../ThinkingHome.Core.Plugins/ThinkingHome.Core.Plugins.csproj" />
    </ItemGroup>
</Project>
