<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="../Package.xml" />
    <PropertyGroup>
        <Description>ThinkingHome plugin which store TelegramBot chats data.</Description>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\ThinkingHome.Core.Plugins\ThinkingHome.Core.Plugins.csproj" />
      <ProjectReference Include="..\ThinkingHome.Plugins.Database\ThinkingHome.Plugins.Database.csproj" />
      <ProjectReference Include="..\ThinkingHome.Plugins.TelegramBot\ThinkingHome.Plugins.TelegramBot.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="ThinkingHome.Migrator.Framework" Version="3.10.0" />
    </ItemGroup>

</Project>
